config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'beens#index'
  resources :users, only: %i[new create]
  resources :beens
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/been.rb
class Been < ApplicationRecord
  validates :country_name, presence: true, length: { maximum: 30 }
  validates :farm_name, presence: true, length: { maximum: 30 }

  belongs_to :user
  mount_uploader :been_image, BeenImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true

  has_many :beens

  def own?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'ログインしてください'
  end
end

app/controllers/beens_controller.rb
class BeensController < ApplicationController
  before_action :set_been, only: %i[edit update destroy]

  def index
    @beens = Been.all.includes(:user).order(created_at: :desc).page(params[:page])
  end

  def show
    @been = Been.find(params[:id])
  end

  def new
    @been = Been.new
  end

  def edit; end

  def update
    if @been.update(been_params)
      redirect_to root_url, success: "コーヒー豆「#{@been.country_name}」を更新しました。"
    else
      render :edit
    end
  end

  def create
    @been = current_user.beens.new(been_params)
    if @been.save
      redirect_to root_url, success: "コーヒー豆「#{@been.country_name}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @been.destroy
    redirect_to root_url, success: "コーヒー豆「#{@been.country_name}」を削除しました。"
  end

  private

  def been_params
    params.require(:been).permit(:country_name, :farm_name, :description, :been_image, :been_image_cache)
  end

  def set_been
    @been = current_user.beens.find(params[:id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_url, success: (t '.success')
    else
      flash.now[:alert] = (t '.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, success: (t '.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: (t '.success')
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beens/_form.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      = form_with model: been, local: true do |f|
        = render 'shared/error_messages', object: f.object
        .form-group.mr-20.ml-20
          = f.label :country_name
          = f.text_field :country_name, class: 'form-control', id: 'country_name'
        .form-group.mr-20.ml-20
          = f.label :farm_name
          = f.text_field :farm_name, class: 'form-control', id: 'farm_name'
        .form-group.mr-20.ml-20
          = f.label :been_image
          = f.file_field :been_image, class: 'form-control-file'
          = f.hidden_field :been_image_cache
        .form-group.mr-20.ml-20
          = f.label :description
          = f.text_area :description, class: 'form-control', id: 'been_description'
        - if request.path_info == new_been_path
          = f.submit (t 'defaults.generate'),class: 'btn btn-primary'
        - else
          = f.submit (t 'defaults.update'),class: 'btn btn-primary'

app/views/beens/edit.html.slim
h1 コーヒー豆の編集

= render partial: 'form', locals: { been: @been }

app/views/beens/index.html.slim
.container
  .row
    - @beens.each do |been|
      .card-group.col-sm-12.col-md-6.col-lg-4.mt-5.mb-3
        .card
          = image_tag been.been_image.url, class: 'card-img-top', height: 250
          .card-body
            h5.card-title
              = link_to been.country_name, been_path(been)
            h6.card-title
              = link_to been.farm_name, been_path(been)
            p.card-text = been.description
  = paginate @beens

app/views/beens/new.html.slim
h1 コーヒー豆新規登録

= render partial: 'form', locals: { been: @been }

app/views/beens/show.html.slim
h1 コーヒー豆詳細

.card.mb-3
  = image_tag @been.been_image.url, class: 'card-img-top', height: 450
  .card-body
    h4.card-title = @been.country_name
    h5.card-title = @been.farm_name
    p.card-text = @been.description
    p.card-text.small = @been.created_at
    p.card-text.small = @been.updated_at
    - if current_user.own?(@been)
      = link_to '編集', edit_been_path, class: 'btn btn-primary mr-3'
      = link_to '削除', been_path(@been), method: :delete, data: { confirm: "コーヒー豆「#{@been.country_name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CoffeeMaster
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"

  body
    - if logged_in?
      = render 'shared/header'
    - else
      = render 'shared/before_login_header'
    = render 'shared/flash_message'
    = yield

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-secondary
  = link_to login_path, class: 'navbar-brand' do
    = image_tag 'coffee_logo.png', class: 'top-image'
  #coffee_title.navbar-brand.justify-content-center = t 'defaults.title'
  button.navbar-toggler data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" type="button"
    <span class="navbar-toggler-icon"></span>
  #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
    ul.navbar-nav.justify-content-end
	    li.nav-item.active
        = link_to (t 'defaults.login'), login_path, class: 'nav-link'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error-messages.alert.alert-danger
    ul
      - object.errors.full_messages.each do |message|
        li = message

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  .alert.alert-success = message
/ なぜが展開ができない？

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-secondary
  = link_to root_path, class: 'navbar' do
    = image_tag 'coffee_logo.png', class: 'top-image'
  #coffee_title.navbar-brand.d-flex.justify-content-center = t 'defaults.title'
  button.navbar-toggler data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" type="button"
    <span class="navbar-toggler-icon"></span>
  #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
    ul.navbar-nav
	    li.nav-item.active
        = link_to (t 'defaults.mypage'), '#', class: 'nav-link'
        = link_to (t 'defaults.new_been'), new_been_path, class: 'nav-link'
	    li.nav-item.dropdown
        = link_to (t 'defaults.game_index'), '#', 
        class: 'nav-link dropdown-toggle',
        id: 'navbarDropdownMenuLink',
        'data-toggle': :dropdown,
        'aria-haspopup': 'true',
        'aria-expanded': 'false',
        'data-reference': 'parcent'
        .dropdown-menu aria-labelledby='navbarDropdownMenuLink'
          = link_to 'ぷよコーヒー', '#', class: 'dropdown-item'
          = link_to 'コーヒー衰弱', '#', class: 'dropdown-item'
	    li.nav-item
        = link_to (t 'defaults.logout'), logout_path, method: :delete, class: 'nav-link'

app/views/user_sessions/new.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 = t '.login'
      = form_with url: login_path, method: :post, local: true do |f|
        .form-group
          = f.label :email, User.human_attribute_name(:email)
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password, User.human_attribute_name(:password)
          = f.password_field :password, class: 'form-control'
        .actions
          = f.submit (t '.login'), class: 'btn btn-primary'
        .text-center.mt-10
          = link_to (t '.to_register_page'), new_user_path, class: 'mr-5'
          = link_to (t '.password_forget'), '#'

app/views/users/new.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 = t '.signup'
      = form_with model: @user, local: true do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control'
        .d-flex.justify-content-center
          = f.submit (t 'defaults.generate'), class: 'btn btn-primary'
        .text-right
          = link_to (t '.to_login_page'), login_path